title: "Ethan Noble's Portfolio"
author: Ethan Noble
email: ethan.noble23@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Portfolio description

# social links
github_username:  runcible-spoon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
